# Site settings
title: Kanosonic's Blog
SEOTitle: Kanosonic's Blog | Digital IC Design
description: "Xidian University student | Digital IC Design"
url: "https://kanosonic.github.io"
baseurl: ""
permalink: /:title/

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Paginate
paginate: 5
paginate_path: /page:num/

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Author info
github_username: kanosonic
email: kanosonic0912@gmail.com

# Sidebar
sidebar: true
sidebar-about-description: "Xidian University Student | Digital IC Design"
sidebar-avatar: https://avatars.githubusercontent.com/u/244021648?s=200&v=4

# Featured Tags
featured-tags: false

# MathJax
page-mathjax: false